# <center>Pandas Assignment</center>

Import pandas and numpy with their aliases

In [38]:
import pandas as pd
import numpy as np

Create a variable a = pd.Series([ 100, 200, 300, 400])

In [39]:
# a = 

a = pd.Series([100, 200, 300, 400])

Print a, and data type

In [40]:


print(a)
print(type(a))

0    100
1    200
2    300
3    400
dtype: int64
<class 'pandas.core.series.Series'>

Using indexing access the element 300 from the series a.

In [41]:
a[2]

np.int64(300)

What are the values of index for series a?

In [42]:

a.index

RangeIndex(start=0, stop=4, step=1)

Change the index to  ['c', 'a', 'b', 'd']

In [43]:

a.index = ['c', 'a', 'b', 'd']
print(a)

c    100
a    200
b    300
d    400
dtype: int64

Access the value in the series with index 'd'

In [44]:

a['d']

np.int64(400)

Sort the values wrt to the index and print it

In [45]:

a.sort_index()

a    200
b    300
c    100
d    400
dtype: int64

Create a new Pandas Series b having index as 'e', 'f', and 'g' and value 800,450,100 and print it

In [46]:
# b = 

b = pd.Series([800, 450, 100], index=['e','f','g'])
print(b)

e    800
f    450
g    100
dtype: int64

Append b series at the end of a series

In [47]:
# a =

a = pd.concat([a,b])

In [48]:
#print a again after appending b into it

print(a)

c    100
a    200
b    300
d    400
e    800
f    450
g    100
dtype: int64

Sort the values in descending order of a and print the index of the sorted series

In [49]:
# a = 

sorted_series = a.sort_values(ascending=False)

In [50]:
print(sorted_series.index)

Index(['e', 'f', 'd', 'b', 'a', 'c', 'g'], dtype='object')

## Pandas DataFrame

### Part 1

Create a pandas dataframe df from the series 'a' that we used in the last section, print the dataframe

In [51]:
# df = 

df = pd.DataFrame(a)

In [52]:
print(df)

     0
c  100
a  200
b  300
d  400
e  800
f  450
g  100

What is the shape of the datafarme <br>
(also, what does it imply?)

In [53]:

df.shape

(7, 1)

Hey! remember shape (7,1) implies dataframe has 7 rows and 1 column.

What is the index of the dataframe, is it same as the series 'a'

In [54]:
# yep its same as the series.

df.index

Index(['c', 'a', 'b', 'd', 'e', 'f', 'g'], dtype='object')

print the head and tail of the dataframe. <br>
Additional - (what does head and tali represent?)

In [55]:

df.head()

     0
c  100
a  200
b  300
d  400
e  800

In [56]:


df.tail()

     0
b  300
d  400
e  800
f  450
g  100

Rename the column of the dataframe as 'points'

In [57]:

df.columns = ['points']
print(df)

   points
c     100
a     200
b     300
d     400
e     800
f     450
g     100

Create another Series 'fruits', which contains random names of fruits from ['orange','mango','apple']. The series should contain 7 elements, randomly selected from ['orange','mango','apple']

In [58]:
#Create fruits array

# fruits =



fruits = pd.Series(np.random.choice(['orange','mango','apple'],7))

In [59]:
#Create series fruits out of fruits array

# fruits =
fruits.index = df.index

Change the index of fruits to the index of dataframe df

In [60]:




df['fruits'] = fruits

Add this fruits series as a new column to the dataframe df with its column name as 'fruits'
<br>print the head of the dataframe to verify

In [61]:

print(df.head())

   points fruits
c     100  apple
a     200  mango
b     300  mango
d     400  mango
e     800  mango

## Pandas Concatenation

Create a dataframe  d1 where the cols are  ‘city’ : [‘Chandigarh’, ‘Delhi’, ‘Kanpur’, ‘Chennai’, ‘Manali’ ] and ‘Temperature’ : [15, 22, 20, 26,-2]

In [62]:
# d1 = 


d1 = pd.DataFrame({
    'city':['Chandigarh','Delhi','Kanpur','Chennai','Manali'],
    'Temperature':[15,22,20,26,-2]
})

Print(d1)

In [63]:

print(d1)

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

What is the shape of d1.

In [64]:



d1.shape

(5, 2)

Set city = d1['city']

In [65]:


city = d1['city']

print city <br>
What is the type of city.

In [66]:

print(city)
print(type(city))

0    Chandigarh
1         Delhi
2        Kanpur
3       Chennai
4        Manali
Name: city, dtype: object
<class 'pandas.core.series.Series'>

Create another datafeame 'd2' where the columns are <br>
'city' - ['Bengalaru','Coimbatore','Srirangam','Pondicherry'] <br>
'Temperature' - [24,35,36,39]

In [67]:
# d2 = 

d2 = pd.DataFrame({
    'city':['Bengalaru','Coimbatore','Srirangam','Pondicherry'],
    'Temperature':[24,35,36,39]
})

print the shape of this dataframe

In [68]:
d2.shape

(4, 2)

merge the two dataframes together, save it in a new dataframe named 'd3'

In [69]:
# d3 = 
d3 = pd.concat([d1,d2], ignore_index=True)
print(d3)

          city  Temperature
0   Chandigarh           15
1        Delhi           22
2       Kanpur           20
3      Chennai           26
4       Manali           -2
5    Bengalaru           24
6   Coimbatore           35
7    Srirangam           36
8  Pondicherry           39

Select the part of the dataframe such that it contains cities wherer temp is less then or equal to 20 <br>
How many cities are there?

In [70]:



low_temp = d3[d3['Temperature'] <= 20]
print(low_temp)

len(low_temp)

         city  Temperature
0  Chandigarh           15
2      Kanpur           20
4      Manali           -2

3

Select the part of the dataframe such that it contains the cities where tempearature greater than or equal to 35

In [71]:

high_temp = d3[d3['Temperature'] >= 35]
print(high_temp)

          city  Temperature
6   Coimbatore           35
7    Srirangam           36
8  Pondicherry           39

## Applying functions to columns and creating new columns

We need to create another column in d3, which contains  a boolean value for each city to indicate whether it's a union territory or not. 
- HINT: Chandigarh, Pondicherry and Delhi are only 3 union territories here.

In [72]:
# write function here

# def is_ut(x):
    
#     # write code below
    
# d3['is_ut'] = 
ut = ['Chandigarh','Delhi','Pondicherry']

d3['Union_Territory'] = d3['city'].isin(ut)

In [73]:
# print d3
print(d3)

          city  Temperature  Union_Territory
0   Chandigarh           15             True
1        Delhi           22             True
2       Kanpur           20            False
3      Chennai           26            False
4       Manali           -2            False
5    Bengalaru           24            False
6   Coimbatore           35            False
7    Srirangam           36            False
8  Pondicherry           39             True

The temperatures mentioned in ‘Temperature’ column are mentioned in Celsius, we need another column which contains the same in Fahrenheit.

HINT - 
- Define a function c_to_f which takes input temp in celsius and returns a value with temperature in Fahrenheit.
- To check: c_to_f(10) should return 50.

In [74]:
# check function c_to_f(10)

def c_to_f(temp):
    return (temp * 9/5) + 32

In [75]:
# apply function c_to_f to d3 to create a column 'temp_farenhiet'


d3['Temp_F'] = d3['Temperature'].apply(c_to_f)
print(d3)

          city  Temperature  Union_Territory  Temp_F
0   Chandigarh           15             True    59.0
1        Delhi           22             True    71.6
2       Kanpur           20            False    68.0
3      Chennai           26            False    78.8
4       Manali           -2            False    28.4
5    Bengalaru           24            False    75.2
6   Coimbatore           35            False    95.0
7    Srirangam           36            False    96.8
8  Pondicherry           39             True   102.2

## Indexing and selecting rows in DataFrame

Select subset of the dataframe d1 such that it contains the cities which are union territories.

In [76]:

d3[d3['Union_Territory'] == True]

          city  Temperature  Union_Territory  Temp_F
0   Chandigarh           15             True    59.0
1        Delhi           22             True    71.6
8  Pondicherry           39             True   102.2

Select a subset of the dataframe d1 such that it contains the cities which only have temperature above 90 Farenhiet.

In [77]:

d3[d3['Temp_F'] > 90]

          city  Temperature  Union_Territory  Temp_F
6   Coimbatore           35            False    95.0
7    Srirangam           36            False    96.8
8  Pondicherry           39             True   102.2

Select only the first three rows of the dataframe d1.

In [78]:
d3.head(3)

         city  Temperature  Union_Territory  Temp_F
0  Chandigarh           15             True    59.0
1       Delhi           22             True    71.6
2      Kanpur           20            False    68.0

Select all the rows and last two columns in the dataframe.

In [79]:
d3.iloc[:, -2:]

   Union_Territory  Temp_F
0             True    59.0
1             True    71.6
2            False    68.0
3            False    78.8
4            False    28.4
5            False    75.2
6            False    95.0
7            False    96.8
8             True   102.2

## Groupby

In [80]:
# Create a dataframe using dictionary of your choice

# data = 




data = {
    'Department': ['IT','HR','IT','HR','Finance','Finance','IT'],
    'Employee': ['A','B','C','D','E','F','G'],
    'Salary': [50000,40000,60000,45000,55000,52000,58000]
}

df = pd.DataFrame(data)

print(df)

  Department Employee  Salary
0         IT        A   50000
1         HR        B   40000
2         IT        C   60000
3         HR        D   45000
4    Finance        E   55000
5    Finance        F   52000
6         IT        G   58000

In [81]:
# Use Groupby of single column with aggregate sum()

df.groupby('Department')['Salary'].sum()

Department
Finance    107000
HR          85000
IT         168000
Name: Salary, dtype: int64

In [82]:
# Use Groupby of single column with aggregate count()

df.groupby('Department')['Employee'].count()

Department
Finance    2
HR         2
IT         3
Name: Employee, dtype: int64

In [83]:
# Use Groupby of single column with aggregate min() and max()


df.groupby('Department')['Salary'].agg(['min','max'])

              min    max
Department
Finance     52000  55000
HR          40000  45000
IT          50000  60000

In [84]:
# Use Groupby of any 2 columns with aggregate mean()


df.groupby(['Department','Employee'])['Salary'].mean()

Department  Employee
Finance     E           55000.0
            F           52000.0
HR          B           40000.0
            D           45000.0
IT          A           50000.0
            C           60000.0
            G           58000.0
Name: Salary, dtype: float64

In [85]:
# Use Groupby of any 2 columns with aggregate min() and max()

df.groupby(['Department','Employee'])['Salary'].agg(['min','max'])

                       min    max
Department Employee
Finance    E         55000  55000
           F         52000  52000
HR         B         40000  40000
           D         45000  45000
IT         A         50000  50000
           C         60000  60000
           G         58000  58000

## Data Range

Create a pandas daterange where starting date is 1st of January,2020 and end date is 1st of April 2021, store it in a new variable named 'a'

In [86]:
# a = 


a = pd.date_range(start='2020-01-01', end='2021-04-01')

print a

In [87]:


print(a)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2021-03-23', '2021-03-24', '2021-03-25', '2021-03-26',
               '2021-03-27', '2021-03-28', '2021-03-29', '2021-03-30',
               '2021-03-31', '2021-04-01'],
              dtype='datetime64[ns]', length=457, freq='D')

What is the len of a?

In [88]:


len(a)

457

What is the type of a?

In [89]:

type(a)

pandas.core.indexes.datetimes.DatetimeIndex